#!/bin/bash

# Render Deployment Troubleshooting Script

set -e

echo "🔍 Troubleshooting Render Deployment Issues"
echo "=========================================="

# Check if logged in
if ! render whoami &> /dev/null; then
    echo "❌ Not logged in to Render. Please run 'render login' first."
    exit 1
fi

echo "✅ Logged in to Render"

# Check repository access
REPO_URL="https://github.com/Cmilimo-dev/chamahub"
echo "🔍 Checking repository access..."
if curl -s -o /dev/null -w "%{http_code}" "$REPO_URL" | grep -q "200"; then
    echo "✅ Repository accessible: $REPO_URL"
else
    echo "❌ Repository not accessible: $REPO_URL"
fi

# Check branch
echo "🔍 Checking branch..."
git branch -a | grep -q "main" && echo "✅ Main branch exists" || echo "❌ Main branch missing"

# Check render.yaml syntax
echo "🔍 Checking render.yaml syntax..."
if [ -f "render.yaml" ]; then
    echo "✅ render.yaml exists"
    
    # Basic syntax check
    if grep -q "services:" render.yaml && grep -q "databases:" render.yaml; then
        echo "✅ render.yaml has required sections"
    else
        echo "❌ render.yaml missing required sections"
    fi
    
    # Check for repository configuration
    if grep -q "repo:" render.yaml && grep -q "branch:" render.yaml; then
        echo "✅ render.yaml has repository configuration"
    else
        echo "❌ render.yaml missing repository configuration"
    fi
else
    echo "❌ render.yaml not found"
fi

# Check for required files
echo "🔍 Checking required files..."
[ -f "backend-package.json" ] && echo "✅ backend-package.json exists" || echo "❌ backend-package.json missing"
[ -f "server-postgres.js" ] && echo "✅ server-postgres.js exists" || echo "❌ server-postgres.js missing"

# Check if changes are pushed
echo "🔍 Checking git status..."
if git status --porcelain | grep -q .; then
    echo "⚠️  Uncommitted changes detected"
    git status --porcelain
else
    echo "✅ No uncommitted changes"
fi

# Check if branch is up to date
echo "🔍 Checking if branch is up to date..."
git fetch origin
if git status | grep -q "up to date"; then
    echo "✅ Branch is up to date"
else
    echo "⚠️  Branch may not be up to date"
    git status
fi

echo ""
echo "🛠️  SOLUTIONS FOR COMMON ISSUES:"
echo "================================"
echo ""
echo "1. Branch not found error:"
echo "   - Ensure render.yaml has correct repo and branch"
echo "   - Check that repository is public or connected to Render"
echo ""
echo "2. DATABASE_URL environment variable:"
echo "   - This is auto-generated by Render when database is created"
echo "   - Ensure database section exists in render.yaml"
echo "   - Database must be created before web service"
echo ""
echo "3. Build failures:"
echo "   - Check that backend-package.json exists"
echo "   - Ensure server-postgres.js has no syntax errors"
echo "   - Verify Node.js version compatibility"
echo ""
echo "📋 Next steps:"
echo "1. Commit and push any changes"
echo "2. Try deploying again via Render Dashboard"
echo "3. Check Render logs for detailed error messages"
echo ""
echo "🔧 Manual deployment steps:"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New' → 'Blueprint'"
echo "3. Select repository: Cmilimo-dev/chamahub"
echo "4. Review and deploy"
